name: Build and Deploy

on: 
  workflow_dispatch:
  push:

jobs:
  build_and_deploy:
    name: Build and deploy page
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn export out
    - run: cat out/de/home/index.html
