name: Build and Deploy

on: 
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn export out
    - run: cp out/de/home/index.html out/index.html
    - run: bash scripts/deploy.sh
      env:
        FTP_CREDENTIALS: ${{ secrets.FTP_CREDENTIALS }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
